### ISSUE TITLE
fix-lsp-company-prefix removed in spacemacs develop branch

### ISSUE THREAD

**Issue by vidyu** [thanhvg/vue#1]
Hi. The fix-lsp-company-prefix definition was removed in the spacemacs development branch
(https://github.com/syl20bnr/spacemacs/commit/f892ba3091c1c22501948901ad8e1db19de22cb6) and the following line throws an error:
https://github.com/thanhvg/vue/blob/0d9a4049133bc9340b7892714e330f07568b66fb/funcs.el#L51

**Comment by thanhvg** [comment]
Thanks for letting me know. I pushed a fix, can you try it?

**Comment by vidyu** [comment]
Hi. Tested it and it's fixed.
