### ISSUE TITLE
Failing to install in Spacemacs Develop Branch

### ISSUE THREAD

**Issue by Cy-Tek** [thanhvg/vue#2]
When I try to add the vue layer to spacemacs, it just shows up as failing in the tests and doesn't install. Any ideas why?

Btw, I am completely new to spacemacs / emacs in general, so there very well could be something that I'm missing.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16470547/61597825-ec7bb680-abe2-11e9-8ecf-299ddcc5ddae.png">

**Comment by thanhvg** [comment]
When you remove that `vue` line does it work?

This is a private layer. You should clone this repo to `~/.emacs.d/private/vue` first. 
```
cd ~/.emacs.d/private 
git clone https://github.com/thanhvg/vue
```

**Comment by Cy-Tek** [comment]
Awesome! Thank you so much! That makes much more sense now 😁 Thanks for helping me on my journey to emacs! Your plugin works great now that I have it up and running, thank you for all your hard work and your quick response!!
