### ISSUE TITLE
Pull request to add this layer officially to Spacemacs?

### ISSUE THREAD

**Issue by x-ji** [thanhvg/vue#4]
This layer is working great for me. But I spent quite some time before I was able to find it. Most other Vue configurations for Emacs were already outdated. Would you mind opening a PR to Spacemacs so that this becomes an official layer?

Thanks for the great work!

**Comment by thanhvg** [comment]
Thanks, when the other issue you created is done I'll make a PR

**Comment by stradicat** [comment]
Definitely, that would be great; this layer makes Spacemacs a good Vue IDE.
I think people on the `develop` branch would be more than willing to incorporate it.

**Comment by thanhvg** [comment]
Thank you all for your kind intention. I just created the PR https://github.com/syl20bnr/spacemacs/pull/12977
